apiVersion: apps/v1
kind: Deployment

metadata:
  name: novabridge-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: novabridge

  template:
    metadata:
      labels:
        app: novabridge

    spec:
      containers:
      - name: novabridge-container
        image: zoya9545/novabridge-web:v2
        ports:
        - containerPort: 80
